###############################################################################
#
# Makefile for a script (e.g. Python), project 10
#
###############################################################################

# **** Beginning of the actual Makefile ****
all:
	chmod a+x JackAnalyzer